# Generated by Django 4.1.2 on 2022-12-05 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0016_delete_order_address'),
        ('cart', '0002_alter_order_address_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания заказа')),
                ('date_finish', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения заказа')),
                ('price', models.FloatField(null=True, verbose_name='Стоимость заказа')),
                ('address_delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cart.order_address', verbose_name='Адрес доставки')),
                ('status', models.CharField(choices=[('Создан', 'Создан'), ('Отменен', 'Отменен'), ('Согласован', 'Согласован'), ('В пути', 'В пути'), ('Завершен', 'Завершен')], max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['date_create'],
            },
        ),
        migrations.AlterModelOptions(
            name='order_address',
            options={'verbose_name': 'Адрес доставки заказа', 'verbose_name_plural': 'Адрес доставки заказа'},
        ),
        migrations.CreateModel(
            name='Pos_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_book', models.IntegerField(verbose_name='Кол-во книг в заказе')),
                ('price', models.FloatField(verbose_name='Общая стоимость книг')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.book', verbose_name='Книга')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cart.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Позиция в заказе',
                'verbose_name_plural': 'Позиции в заказе',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(through='cart.Pos_order', to='library.book', verbose_name='Книги'),
        ),
    ]
