# Generated by Django 4.1.2 on 2022-12-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_alter_order_address_options_pos_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Создан', 'Создан'), ('Отменен', 'Отменен'), ('Согласован', 'Согласован'), ('В пути', 'В пути'), ('Завершен', 'Завершен')], default='Создан', max_length=150, verbose_name='Статус'),
        ),
    ]
